### ISSUE TITLE
Fel i lösningen?

### ISSUE THREAD

**Issue by toblu302** [SveKub/SveKub.github.io#22]
[Den här sidan](http://www.svekub.org/Losningar/Losning/KanterSistaLagret) säger att Sune-algoritmen ser ut så här:
R U' R' U' - R U2 R'

Alla andra sidor* jag hittade säger att Sune-algoritmen ser ut så här:
R U R' U R U2 R'

* https://www.speedsolving.com/wiki/index.php/Sune
https://cubefreak.weebly.com/2-look-oll.html
https://rubiks-cube-solver.com/how-to-solve/

**Comment by dahermansson** [comment]
Löst med PR #23
